# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true
timezone: Europe/Budapest

# Setup
title:               Please be careful
tagline:             'the cake is a lie'
description:         "Mostly ramblings about software, frameworks, programming languages and open source. Just the usual stuff."
url:                 http://tmichel.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              "Tam√°s Michelberger"
  url:               https://twitter.com/tmichelberger
  email:             tomi.michel@gmail.com
  github:            https://github.com/tmichel

redcarpet:
  extensions:
    - autolink
    - strikethrough
    - no_intra_emphasis
    - footnotes
